pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "SmartAlarm"
include(":app")
include(":core:common")
include(":core:data")
include(":core:alarm")
include(":core:ui")
include(":feature:alarms")
include(":feature:games")
include(":feature:games:calc")
include(":feature:games:memory")
include(":feature:games:equation")
include(":feature:games:sorting")
include(":feature:games:pairs")
include(":feature:games:sequence")
include(":feature:games:stroop")
include(":feature:games:oddoneout")
include(":feature:games:maze")
include(":feature:games:anagram")
include(":feature:games:truefalse")
include(":feature:games:reaction")
include(":feature:games:counter")
include(":feature:games:lights")
include(":feature:games:fifteen")
include(":feature:games:chain")
include(":feature:games:roman")
include(":feature:games:clock")
include(":feature:games:digits")
include(":feature:games:hanoi")
include(":feature:games:targetsum")
include(":feature:games:matrix")
include(":feature:games:mole")
include(":feature:games:pattern")
include(":feature:games:weekday")
include(":feature:games:percent")
include(":feature:games:binary")
include(":feature:games:reverse")
include(":feature:games:capitals")
include(":feature:games:spelling")
include(":feature:games:dice")
include(":feature:games:demo")
include(":feature:records")
include(":feature:profile")
include(":feature:settings")
